steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/flask-note-app:$COMMIT_SHA'
      - '.'
    id: 'Build Docker Image'

  # Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/flask-note-app:$COMMIT_SHA'
    id: 'Push Docker Image'

images:
  - 'gcr.io/$PROJECT_ID/flask-note-app:$COMMIT_SHA'

tags:
  - 'cloud-build'

logging: CLOUD_LOGGING_ONLY
